### ISSUE TITLE
Async api

### ISSUE THREAD

**Issue by simonziegler** [adobe/PDFServices.NET.SDK.Samples#17]
I'm new to using PDFSerices.NET and wonder if you have async calls to your API. At the moment, calling `` is a long running synchronous call that blocks other tasks on my server. Is there a way to unblock this with an async method? Thanks.

**Comment by mguinness** [comment]
It doesn't appear that the [Adobe.PDFServicesSDK](https://www.nuget.org/packages/Adobe.PDFServicesSDK) library provides async methods.  Looking at the package dependencies it uses [RestSharp](https://restsharp.dev/) which does include async support.

Why they didn't make the library async from the get-go is anyone's guess, but I wouldn't hold my breath waiting for Adobe to update it.  Since the library is basically a wrapper over the underlying [Rest API](https://documentcloud.adobe.com/document-services/index.html) you could make your own async calls that way.

**Comment by mguinness** [comment]
> You can also reach out to the Adobe community forum to raise the same: https://community.adobe.com/t5/document-services-apis/ct-p/ct-Document-Cloud-SDK for better tracking.

So instead of tracking an issue in the relevant repo, you suggest to add to a discussion forum where it will get lost in the ether?
